USE [master]
GO
/****** Object:  Database [UrbanWrapper]    Script Date: 2021-08-14 10:02:45 AM ******/
CREATE DATABASE [UrbanWrapper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UrbanWrapper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UrbanWrapper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UrbanWrapper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UrbanWrapper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UrbanWrapper] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UrbanWrapper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UrbanWrapper] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UrbanWrapper] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UrbanWrapper] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UrbanWrapper] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UrbanWrapper] SET ARITHABORT OFF 
GO
ALTER DATABASE [UrbanWrapper] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UrbanWrapper] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UrbanWrapper] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UrbanWrapper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UrbanWrapper] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UrbanWrapper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UrbanWrapper] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UrbanWrapper] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UrbanWrapper] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UrbanWrapper] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UrbanWrapper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UrbanWrapper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UrbanWrapper] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UrbanWrapper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UrbanWrapper] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UrbanWrapper] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UrbanWrapper] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UrbanWrapper] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UrbanWrapper] SET  MULTI_USER 
GO
ALTER DATABASE [UrbanWrapper] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UrbanWrapper] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UrbanWrapper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UrbanWrapper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UrbanWrapper] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UrbanWrapper] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UrbanWrapper] SET QUERY_STORE = OFF
GO
USE [UrbanWrapper]
GO
/****** Object:  Table [dbo].[CustomerFeedbacks]    Script Date: 2021-08-14 10:02:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerFeedbacks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NULL,
	[Feedback] [varchar](max) NULL,
	[FDate] [datetime] NULL,
	[CustomerName] [varchar](50) NULL,
	[InvoiceId] [int] NULL,
	[Rating] [int] NULL,
 CONSTRAINT [PK_CustomerFeedbacks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CustomerOrders]    Script Date: 2021-08-14 10:02:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerOrders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NULL,
	[OrderTotal] [decimal](18, 0) NULL,
	[NumberOfProducts] [int] NULL,
	[OrderDate] [datetime] NULL,
 CONSTRAINT [PK_CustomerOrders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 2021-08-14 10:02:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[Phone] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Invoices]    Script Date: 2021-08-14 10:02:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NULL,
	[InvoiceAmount] [decimal](18, 0) NULL,
	[InvoiceDate] [datetime] NULL,
 CONSTRAINT [PK_Invoices] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 2021-08-14 10:02:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [varchar](50) NULL,
	[Price] [decimal](18, 0) NULL,
	[StockQuantity] [int] NULL,
	[Description] [varchar](50) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_CustomerFeedback_Customer]    Script Date: 2021-08-14 10:02:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_FK_CustomerFeedback_Customer] ON [dbo].[CustomerFeedbacks]
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_CustomerOrder_Customer]    Script Date: 2021-08-14 10:02:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_FK_CustomerOrder_Customer] ON [dbo].[CustomerOrders]
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_Invoice_CustomerOrder]    Script Date: 2021-08-14 10:02:45 AM ******/
CREATE NONCLUSTERED INDEX [IX_FK_Invoice_CustomerOrder] ON [dbo].[Invoices]
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CustomerFeedbacks]  WITH CHECK ADD  CONSTRAINT [FK_CustomerFeedback_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([Id])
GO
ALTER TABLE [dbo].[CustomerFeedbacks] CHECK CONSTRAINT [FK_CustomerFeedback_Customer]
GO
ALTER TABLE [dbo].[CustomerOrders]  WITH CHECK ADD  CONSTRAINT [FK_CustomerOrder_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([Id])
GO
ALTER TABLE [dbo].[CustomerOrders] CHECK CONSTRAINT [FK_CustomerOrder_Customer]
GO
ALTER TABLE [dbo].[Invoices]  WITH CHECK ADD  CONSTRAINT [FK_Invoice_CustomerOrder] FOREIGN KEY([OrderId])
REFERENCES [dbo].[CustomerOrders] ([Id])
GO
ALTER TABLE [dbo].[Invoices] CHECK CONSTRAINT [FK_Invoice_CustomerOrder]
GO
USE [master]
GO
ALTER DATABASE [UrbanWrapper] SET  READ_WRITE 
GO
