//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanWrapper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
